Stratio/egeo-web

src/app/app.component.scss
src/app/layout/layout.component.scss

Solve problem with page scroll
close #16

remove page scroll

---

src/app/layout/layout.component.html
src/app/layout/layout.component.scss

fix styles

---

src/app/layout/layout.component.html
src/app/layout/layout.component.scss

fix styles (cherry-pick)

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

documentation(templates): add issue and pr templates

---

CONTRIBUTING.md
LICENSE

- Documentation
add license and contributing file
Close #32 
-

documentation(project): add license and contributing file

---

.travis.yml

- Improvements.
Improvements on config

refactor(travis): improvement builds

---

scripts/deploy-gh-pages.sh

- Bugfix
Previous script in version have a space

fix read version of gh-pages

---

README.md

- Documentation
Write the readme
Close #39 
- 

docs(readme): write the readme

---

CHANGELOG.md
src/app/+others/main/main.component.html

- Documentation
Update and complete overview content
Close #47 
-

docs(overview): update and complete the content

---

src/app/+components/breadcrumbs/breadcrumbs.component.css
src/app/+components/breadcrumbs/breadcrumbs.component.html
src/app/+components/breadcrumbs/breadcrumbs.component.ts
src/app/+components/breadcrumbs/breadcrumbs.module.ts
src/app/+components/breadcrumbs/breadcrumbs.routing.ts
src/app/+components/breadcrumbs/example-code/breadcrumbs.html.txt
src/app/app.routing.ts
src/app/layout/layout.model.ts
src/assets/langs/en.json
src/assets/langs/es.json

feat(Breadcrumbs): Add Breadcrumbs example

---

src/app/layout/layout.component.html
src/app/layout/layout.component.scss
src/app/layout/layout.component.ts
src/app/layout/layout.model.ts
src/app/layout/layout.service.ts

- Feature
combo for navigate between versions
close #65 close #61 

feat(layout): combo for navigate between versions

---

config/webpack/webpack.dev.js
src/app/+overview/changelog/changelog.component.ts
src/app/+overview/main/main.component.scss
src/app/app.component.scss
src/app/app.routing.ts
src/app/layout/layout.component.ts
src/app/layout/layout.service.ts

styles fix and prevent call github api if we are in development

fix(styles): some style fix

---

package.json

- Bugfix vertical menu
Update theme dependencies for fix vertical menu styles

fix(dependencies): update theme dep for fix vertical menu styles

---

CHANGELOG.md
src/app/+components/switch/example-code/switch.html.txt
src/app/+components/switch/switch.component.html
src/app/+components/switch/switch.component.scss
src/app/+components/switch/switch.component.ts
src/app/+components/switch/switch.module.ts
src/app/+components/switch/switch.routing.ts
src/app/app.routing.ts
src/app/layout/layout.model.ts
src/assets/langs/en.json

- New component example
Add switch example

feat(st-switch): Add switch example

---

CHANGELOG.md
src/app/+components/table/table.component.ts

- Bugfix
Change header item type to st-table component example

fix(st-table): Change header item type to st-table component example

---

package.json
src/app/+components/breadcrumbs/breadcrumbs.component.ts
src/app/+components/input/input.component.html
src/app/+components/input/input.component.scss
src/app/+components/radio-menu/radio-menu.component.ts
src/app/+components/spinner/spinner.component.ts
src/app/+components/textarea/textarea.component.html
src/app/+components/textarea/textarea.component.scss
src/app/+overview/main/main.component.scss
src/app/+services/regexp/regexp.component.html
src/app/+themes/stratio/grid/grid.component.html
src/app/+themes/stratio/grid/grid.component.ts
src/app/+themes/stratio/typography/typography.component.html
src/app/app.component.scss
src/app/app.module.ts
src/app/app.routing.ts
src/app/grid-demo/grid-demo.component.html
src/app/grid-demo/grid-demo.component.scss
src/app/grid-demo/grid-demo.component.ts
src/app/grid-demo/grid-demo.module.ts
src/app/grid-demo/grid-demo.routing.ts
src/app/layout/layout.component.scss
src/app/shared/api-doc/shared/parameters-table/paramenters-table.component.scss

- Bugfix
Solve some problems with styles, open grid in a independent view and some general improvements

style(all): improvements and bugfix

---

CHANGELOG.md
src/app/+components/table/table.component.ts

- Bugfix
Fix type of table header

fix(st-table): Fix type of table header

---

src/app/+components/dropdown/dropdown.component.ts
src/app/+components/two-list-selection/example-code/two-list-selection.html.txt
src/app/+components/two-list-selection/example-code/two-list-selection.model.ts.txt
src/app/+components/two-list-selection/two-list-selection.component.html
src/app/+components/two-list-selection/two-list-selection.component.scss
src/app/+components/two-list-selection/two-list-selection.component.ts
src/app/app.routing.ts
src/app/layout/layout.model.ts
src/assets/langs/en.json
src/styles/global.scss

- New component.
Add documentation for two-list

feat(two-list): add documentation for two-list

---

CHANGELOG.md
src/app/app.component.scss
src/app/shared/api-doc/api-doc.component.scss

Apply new colors, font-sizes, separations, etc.
Close #84
- Bugfix
Apply new colors, font-sizes, separations, etc. following the zeplin design
- 

fix(app and api-doc): fix bad title styles

---

CHANGELOG.md
src/app/layout/layout.component.html
src/app/layout/layout.component.scss

add a footer
Close #81
- New feature
Add a footer
-

feat(footer): add a footer

---

src/app/shared/api-doc/shared/api-doc.model.ts
src/app/shared/api-doc/shared/parameters-table/paramenters-table.component.html
src/app/shared/api-doc/shared/parameters-table/paramenters-table.component.scss

#99
- feature
Add deprecated tag for inputs.

feat(DOC): Add deprecated tag for inputs

---

CHANGELOG.md
src/app/+components/breadcrumbs/breadcrumbs.component.ts
src/app/+components/button/button.component.ts
src/app/+components/info-box/info-box.component.ts
src/app/+components/info-card/info-card.component.ts
src/app/+components/radio-menu/radio-menu.component.ts
src/app/+components/switch/switch.component.ts
src/app/+components/tabs-vertical/tabs-vertical.component.ts
src/app/+components/toggle-button/toggle-button.component.ts
src/assets/langs/en.json

- Fix translation
Add minor changes to some translations

fix(translation): Fix some translations

---

package.json
src/app/+components/combobox/combobox.component.html
src/app/+components/combobox/combobox.component.scss
src/app/+components/combobox/combobox.component.ts
src/app/+components/combobox/combobox.module.ts
src/app/+components/combobox/combobox.routing.ts
src/app/+components/combobox/example-code/combobox.html.txt
src/app/app.routing.ts
src/app/layout/layout.model.ts
src/assets/langs/en.json

- New component
Add combobox documentation

feat(combobox): Add combobox documentation

---

CHANGELOG.md
src/app/+components/page-title/example-code/page-title.html.txt
src/app/+components/page-title/page-title.component.html
src/app/+components/page-title/page-title.component.ts

Update page title documentation

docs(page-title): Update page title documentation

---

CHANGELOG.md
src/app/+components/radio-menu/example-code/radio-menu.html.txt
src/app/+components/radio-menu/radio-menu.component.html
src/app/+components/radio-menu/radio-menu.component.ts

Update Radio Menu documentation
- [ X ] Have changelog.md updated
- [ X ] Have 3 spaces indentation

docs(Radio Menu): Update radio menu documentation

---

CHANGELOG.md
src/app/+components/tip/example-code/tip.html.txt
src/app/+components/tip/tip.component.html
src/app/+components/tip/tip.component.ts
src/app/+components/tip/tip.module.ts
src/app/+components/tip/tip.routing.ts
src/app/app.routing.ts
src/app/layout/layout.model.ts
src/assets/langs/en.json

feat(st-tip): Creat Tip doc

---

package.json
src/app/+components/search/search.component.html
src/app/+components/search/search.component.ts

- Update
Add autocomplete options and notify deprecated parameters

feat(st-search): update st-search docs

---

CHANGELOG.md
src/app/+components/input/input.component.html
src/app/+components/input/input.component.ts

- Improvement
Add an example for number inputs with min and max validations

feat(st-input): Add an example for number inputs with min and max validations

---

CHANGELOG.md
src/app/+components/radio-menu/radio-menu.component.ts

- Refactor
Add minor changes to the radio menu example

refactor(st-radio-menu): Add minor changes to the radio menu example

---

src/app/+components/item-list/example-code/item-list.html.txt
src/app/+components/item-list/example-code/item-list.model.ts.txt
src/app/+components/item-list/item-list.component.html
src/app/+components/item-list/item-list.component.scss
src/app/+components/item-list/item-list.component.ts
src/app/+components/item-list/item-list.module.ts
src/app/+components/item-list/item-list.routing.ts
src/app/app-routing.module.ts
src/app/layout/layout.model.ts
src/assets/langs/en.json

Add documentation for item-list component

feat(item-list): Add documentation for item-list component

---

package.json
src/app/layout/layout.component.html

fix: fix footer broken image

---

src/app/layout/layout.component.html
src/app/layout/layout.component.ts

fix: fix selected version

---

.angular-cli.json
src/app/layout/layout.component.html
src/app/layout/layout.component.ts
src/app/layout/layout.service.ts

window.location from all the life

---

CHANGELOG.md
src/app/+components/switch/switch.component.ts

Close #CCT-123
- Bugfix
Add missing inputs/outputs and fix bad descriptions to switch example

fix(st-switch): St-Switch output documentation missing

---

CHANGELOG.md
src/app/+components/breadcrumbs/breadcrumbs.component.html
src/app/+components/button/button.component.html
src/app/+components/dropdown/dropdown.component.html
src/app/+components/help/help.component.html
src/app/+components/info-box/info-box.component.html
src/app/+components/info-card/info-card.component.html
src/app/+components/item-list/item-list.component.html
src/app/+components/modal/modal.component.html
src/app/+components/page-title/page-title.component.html
src/app/+components/pagination/pagination.component.html
src/app/+components/search/search.component.html
src/app/+components/tabs-horizontal/tabs-horizontal.component.html
src/app/+components/tabs-vertical/tabs-vertical.component.html
src/app/+components/tip/tip.component.html
src/app/+themes/stratio/colors/colors.component.html
src/app/+themes/stratio/grid/example-code/grid.html.txt
src/app/+themes/stratio/grid/grid.component.html
src/app/+themes/stratio/typography/typography.component.html
src/app/grid-demo/grid-demo.component.html
src/app/layout/header/header.component.html
src/app/layout/layout.component.html
src/app/shared/api-doc/api-doc.component.html
src/app/shared/api-doc/shared/parameters-table/paramenters-table.component.html

- Refactor
Refactor egeo web and egeo examples to 12 columns grid.

refactor(grid): Grid refactor

---

src/app/+components/button/button.component.html
src/app/+components/button/button.component.scss
src/app/+components/button/button.component.ts

- Bugfix
Load two example as egeo-demo library

fix(buttons): Load two example as egeo-demo library

---

.angular-cli.json

[CCT-165] feat(Dev): Change default port

---

main.js

fix(default version)[NA]: Fix redirection to the last version
